# Generated by Django 5.0 on 2024-04-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0012_bill_history_bill_reference_billitems_debitnote_debitnote_comments_debitnote_history_debitnote_item_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitnote',
            name='bills',
        ),
    ]
