# Generated by Django 5.0 on 2024-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0013_remove_debitnote_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='action',
            field=models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Action',
            field=models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=10, null=True),
        ),
    ]
