# Generated by Django 5.0 on 2024-04-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0014_recurring_bills_action_alter_bill_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Action',
            field=models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited')], default='Created', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurring_bills',
            name='action',
            field=models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited')], default='Created', max_length=10),
        ),
    ]
