# Generated by Django 5.0 on 2024-04-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0015_alter_bill_action_alter_recurring_bills_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='Action',
            new_name='debitNoteaction',
        ),
        migrations.RenameField(
            model_name='recurring_bills',
            old_name='action',
            new_name='debitNoteaction',
        ),
    ]
